### ISSUE TITLE
Route does not fail while while dragging marker

### ISSUE THREAD

**Issue by planemad** [Project-OSRM/osrm-frontend-v2#133]
While dragging a marker to an unroutable area, the suggested route continues to display the last successful route till the marker is dropped. This behavior makes it very hard to spot the exact point of failure while doing directions QA.

![untitled](https://cloud.githubusercontent.com/assets/126868/10334879/ec482e02-6d0a-11e5-9f1f-1a2de5454e17.gif)
http://map.project-osrm.org/?z=17&center=43.653788%2C-79.380233&loc=53.544389%2C-113.490927&loc=43.653691%2C-79.380566&hl=en&ly=&alt=&df=&srv=

In the previous frontend the route would update will dragging the marker. Lets have this behavior back..
![](https://cloud.githubusercontent.com/assets/126868/10047108/278e2bb0-622a-11e5-9cd4-37121ca33f62.gif)

cc @amyleew @shvrm

**Comment by perliedman** [comment]
I'm pretty sure this issue really relates to LRM, so I've created https://github.com/perliedman/leaflet-routing-machine/issues/167 for this.

Since I'm currently mostly doing LRM in my free time, any help with this would of course be very much appreciated.

**Comment by perliedman** [comment]
I've investigated this a bit, and I don't think there's an exact solution to the problem. It would be interesting to know how the old frontend worked.

The issue is really this:
- When a waypoint is located in an "unroutable" area, OSRM will still find the nearest routable node, and route from there
- Because the nearest node is used for routing, there's no such thing as an "unroutable area", or at least there is no way for LRM to tell - actual, routed waypoints will often be located some distance from where the user placed them, and OSRM will still route
- The new frontend uses a `waypointMode` called `snap`, that means waypoints will be moved to the actual, routed waypoint locations once routing finishes - this is not done during drag, however, which makes it less clear what is happening
- If you do the same routing with `waypointMode` set to `extend`, it becomes much more visibly clear which part is actually routed

My guess is that the old frontend used some sort of threshold - if the actual, routed waypoint was further away from the placed waypoint, the route was simply discarded.

I'm still a fan of `waypointMode: extend`, but I would be interested in other ideas of how this could work .

**Comment by planemad** [comment]
@perliedman to clarify, the most important task while debugging a failed route is to find the exact point of failure. This allows us to investigate why the route failed at that exact point.

This is how it used to work in the previous frontend.
![](https://cloud.githubusercontent.com/assets/126868/10047108/278e2bb0-622a-11e5-9cd4-37121ca33f62.gif)

**Comment by perliedman** [comment]
Yep, I think I get it!

Weirdly enough, I couldn't find any unroutable areas around where I live, even if I placed waypoints far out in the sea - OSRM would always return a route, even though several kilometers from any road or ferry route. Because of this, I misunderstood the issue.

However, when actually trying the example you provided above, I can get OSRM to refuse to route me.

Anyway, a fix for when OSRM actually doesn't return a route is available in https://github.com/perliedman/leaflet-routing-machine/commit/001a83748439ada4176f0faaab4f2a5493edfc16

**Comment by TheMarex** [comment]
@perliedman yeah the intended behavior is that it always returns a route. But sometimes we hit edge cases where this is not the case. This helps to debug this.

Thanks! :+1:

**Comment by amyleew** [comment]
Thanks for the fix @perliedman

**Comment by perliedman** [comment]
I think this should be closed, since the site runs LRM 2.6.1, which contains the fix mentioned above.

**Comment by TheMarex** [comment]
@perliedman thanks for digging this up! :+1:
