### ISSUE TITLE
Almost completely broken in FF45 Beta (second point does not complete)

### ISSUE THREAD

**Issue by mcepl** [Project-OSRM/osrm-frontend-v2#157]
Hi,

when opening your page in Firefox 45 (Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0) I get page displayed, but when I try to find a route, I fail. When I enter to the first box "rue gambetta, treguier" and press ENTER, the location gets displayed, but when I enter to the second box "roissy-en-france" (hoping to get [near the airport Charles de Gaulle](http://osm.org/go/0BPlKcx?relation=530470)) and press ENTER, I get no response from the site.

The same goes for Firefox Nightly (Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0).

**Comment by yuryleb** [comment]
This route with specified start/end points seems to work now - I got http://map.project-osrm.org/?z=7&center=49.239121%2C0.873413&loc=48.785381%2C-3.232293&loc=49.002529%2C2.514152&hl=fr&alt=0

UPD: Maybe empty route could be due to unsupported Array.find() method by Firefox as by IE - recently fixed with #234. But actually there are no lane indications (where this method is being called) on this route at this time.

**Comment by mcepl** [comment]
Yes, it works now with 52.1.0. Thank you.
