### ISSUE TITLE
Waypoint input needs multiple Enter presses before doing its geocoding business

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-frontend-v2#172]
Enter "Monaco"
Press Enter _nothing happens_
Press Enter _centers on Monaco_

It seems like the console is also full of debug output, which may or may not help:

```
Exception InvalidInt: "undefined" is not a valid integer. bundle.js:11:17152
Object { center: Object, zoom: 13, waypoints: Array[0], language: "en", alternative: 0, layer: Object } bundle.js:11:19939
Object { center: Object, zoom: 13, waypoints: Array[0], language: "en", alternative: 0, layer: Object } bundle.js:11:19112
NetworkError: A network error occurred.
```

and then some more Objects.

/cc @amyleew @TheMarex

**Comment by perliedman** [comment]
I think what you describe is a result of Nominatim sometimes being quite slow to respond. I've been thinking about adding a spinner or similar when doing geocoding lookups in LRM, but never gotten around to it. The feedback should at least be improved in some way.

**Comment by daniel-j-h** [comment]
I don't think this is the case here. Check it out for yourself:

Enter "Monaco"
Press Enter _nothing happens_
Wait for Minutes _nothing happens_
Press Enter _centers on Monaco instantly_

**Comment by batpad** [comment]
This is a bit silly.

Did some tracking down, and here's what seems to be happening:

The `enter` does trigger the request to Nominatim and results are returned. It then puts the results into a table, I guess for the user to be able to pick the one they want: https://github.com/perliedman/leaflet-routing-machine/blob/master/src/autocomplete.js#L60

This table seems to get created on the DOM just fine, and I imagine selecting the item one wants from the table probably works as well. The problem is, the table is never visible, I guess because of CSS issues 😆 

Of course, the second `enter` then triggers the selecting of the first option and actually shows it on the map. So this *seems* to me to be CSS - will hack around some more, simple setting of high z-indexes did not seem to do the trick.

Does anyone know if this ever worked? I can try looking up past commits to track it down then.

**Comment by batpad** [comment]
So, it turns out the `leaflet-routing-machine.css` file was never being included.

I have created a branch that includes it: https://github.com/batpad/osrm-frontend/tree/double-entendre

Here, the geocoding / double-enter functionality seems to be fixed - it now shows a list of options and one can select the correct one, etc. The problem is, including this CSS seems to have had minor styling side-effects - the inputs look a bit larger / weird, and the X icons are not aligned properly.

Is anyone who maybe more familiar with the CSS here able to look at it? cc @amyleew
