### ISSUE TITLE
Not able to run frontend osrm-5-0 against osrm-backend-v5.0.0-rc.2

### ISSUE THREAD

**Issue by noblige** [Project-OSRM/osrm-frontend-v2#173]
I can see requests reaching backend and response is sent out, but no polyline nor turnlist is displayed. Sample response from backend:

```
{"code":"Ok","routes":[{"legs":[{"duration":209.7,"steps":[],"distance":2811}],"duration":209.7,"distance":2811}],"waypoints":[{"hint":"9wgAgPgIAIA7AAAAEgAAAJgAAAB4AAAAJQAAAM4DAADNAwAAMgAAAAiYkQeHUT0CLpiRB0RSPQIDAAEB_ub05w==","name":"우정국로","location":[126.982152,37.572999]},{"hint":"FhIAgP___3_eAAAAFgAAAGQAAAAAAAAAAAAAADIlAAAAHAAAMgAAAFDkkQcQLz0CCeSRBw4vPQIAAAEB_ub05w==","name":"퇴계로51길","location":[127.00168,37.564176]}]}
```

**Comment by TheMarex** [comment]
@noblige the frontend does not support v5 yet. You can help by porting https://github.com/perliedman/leaflet-routing-machine

**Comment by noblige** [comment]
perliedman/leaflet-routing-machine#225

**Comment by perliedman** [comment]
I just pushed preliminary OSRM 5.0 / API v1 support to Leaflet Routing Machine. I haven't made a release, since I would like some testing and comments first.

It currently only has limited support for OSRM 5's more advanced step instructions, and I think that's an area that will have to be improved, but it's also a bit complicated because of multiple language support and the fact that changes have to be compatible with other routing plugins like GraphHopper, Mapbox, etc.

Testing, feedback and fixes would be very welcome, since I will not have a lot of time to put into this myself.
