### ISSUE TITLE
Demo website contains data only for Afrika

### ISSUE THREAD

**Issue by noenandre** [Project-OSRM/osrm-frontend-v2#180]
Trying to use http://map.project-osrm.org/ in Europe, and it will snap to the closest road in Afrika.
A look at http://map.project-osrm.org/ confirms the problem.

**Comment by daniel-j-h** [comment]
@TheMarex is currently using the demo server to track down a data issue / OSRM having hiccups with garbage data. Turns out there is a particular mis-tagging triggering this which was introduced in the Geofabrik Egypt dataset.

Closing here as not actionable for us. We know the demo server is currently having a hard time and we're working on fixing all issues. As usual, keep in mind it's a demo server and we want it to break. That's the reason it's on latest OSRM master and re-processing the latest planet every day.

Reference: https://github.com/Project-OSRM/osrm-backend/issues/2706#issuecomment-236145113
