### ISSUE TITLE
raw html and no styling

### ISSUE THREAD

**Issue by abeck87** [Project-OSRM/osrm-frontend-v2#210]
I pulled this repo down to a centos 7 machine and ran the npm install and start commands. When hitting the server via Chrome on the exposed 9966 port all that is returned is the raw index.html file. 

Am I missing or doing something wrong? I was hoping to see the leaflet plugin in action with the ORSM map data. 

Thanks.

**Comment by daniel-j-h** [comment]
The demo server is currently down, maybe that's your issue. Otherwise, `npm start` should spawn up a local HTTP server and serve Map + text input + instructions. You can point the frontend to your local routing engine instance (check `src/leaflet_options.js` and you are good to go.

For a local backend you can either compile it yourself (see `osrm-backend` repository Wiki for instructions) or use `npm install osrm` to get NodeJs bindings which also bundle pre-build binaries at `./node_modules/osrm/lib/binding/osrm-*`.

**Comment by abeck87** [comment]
Figured it out. I had it fronted by nginx. Looking at our ngnix config i had to uncomment a header security setting "add_header X-Content-Type-Options nosniff;". Now its working.

**Comment by daniel-j-h** [comment]
Perfect!
