### ISSUE TITLE
Why is webpage map display available when no internet connect

### ISSUE THREAD

**Issue by kkyiss** [Project-OSRM/osrm-frontend-v2#267]
Hello
I've already connected the osrm-frontend server with my  osrm-backend server and host at the same PC.
My question is: 
**When there is no internet connected, the osrm-frontend server couldn't request map.png(?) and should just display blank instead.**

**However, with some zoom level, I can still see the map display well 
How is it working?**

tks for any replies

**Comment by daniel-j-h** [comment]
If you are using the frontend and pointing it to your local routing engine as per

https://github.com/Project-OSRM/osrm-frontend#changing-backends

the map tiles are still getting loaded over the internet.

If you want offline maps you have to look into e.g. hosting your tiles offline on your machine, too.

You're probably seeing some map tiles because they're cached in your browser.

**Comment by kkyiss** [comment]
I'll try to clean my cached 
thanks you @daniel-j-h !
